### PR TITLE
Define parameter %{version} for rpmspec call in build-deps.sh 

### LINKED ISSUE #3010: Image refresh for rhel-7-9
Image refresh for rhel-7-9
 * [ ] FAIL: image-refresh rhel-7-9

### LINKED ISSUE #3012: Image refresh for centos-7
Image refresh for centos-7
 * [ ] FAIL: image-refresh centos-7

### PR DESCRIPTION
**Pull request by skobyda**
Fixes #3012
Fixes #3010

 * [x] image-refresh centos-7
 * [x] image-refresh rhel-7-9

### CODE REVIEW

File: images/scripts/lib/build-deps.sh [hunk 1]
```diff
@@ -14,12 +14,13 @@ OS_VER="$1"
 # most images use cockpit.spec from main branch, but there's a RHEL 7 stable branch with a completely different layout
 case "$OS_VER" in
     rhel*7|centos*7)
-        spec=$($GET "$COCKPIT_GIT/rhel-7.9/tools/cockpit.spec" |
-            sed 's/%{npm-version:.*}/0/; /Recommends:/d; s/build_optional 0/build_optional 1/')
+        url=$GET "$COCKPIT_GIT/rhel-7.9/tools/cockpit.spec"
```
Comment (martinpitt) [inline images/scripts/lib/build-deps.sh:17]: This can't work, it's a syntax error. Possibly you want to move the `$GET` into the next line?

```
❱❱❱ images/scripts/lib/build-deps.sh 'centos 7'
images/scripts/lib/build-deps.sh: line 17: https://raw.githubusercontent.com/cockpit-project/cockpit/rhel-7.9/tools/cockpit.spec: No such file or directory
```

**Review by martinpitt — CHANGES_REQUESTED** [review]
See above

**Comment by skobyda** [comment]
> How about this fix? It defines the missing `%{version}` that it's complaining about.

Works for me locally. 
Although one thing I don't understand, how does supplying `-D 'version 0'` parameter fixed the `Too many levels of recursion in macro expansion` expansion error?

**Comment by martinpitt** [comment]
Because the relevant error message from `./images/scripts/lib/build-deps.sh 'centos 7'` is this:

    warning: line 88: Possible unexpanded macro in: Version:        %{version}

**Comment by martinpitt** [comment]
Thanks! Trying a centos-7 image refresh, if that works, I'll trigger rhel-7-9 as well.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3105-20220318-110808/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20220318-114545

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-9.
Log: https://logs.cockpit-project.org/logs/image-refresh-3105-20220318-114545/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpit-project/bots/commits/image-refresh-centos-7-20220318-122424

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-3105-20220318-123333/

**Comment by skobyda** [comment]
centos-7 image refresh succeed, trigerring rhel7-9

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20220318-131616

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-3105-20220318-131717/

**Comment by martinpitt** [comment]
Thanks! I rebased and committed the refreshed images. Let's see that they actually work.

**Comment by cockpituous** [comment]
image-refresh rhel-7-9 done: https://github.com/cockpit-project/bots/commits/image-refresh-rhel-7-9-20220318-134545

**Comment by martinpitt** [comment]
Argh, insights [regressed on rhel-7-9](https://logs.cockpit-project.org/logs/pull-3105-20220318-141423-a6687942-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html#60-2). Possibly #3050 or #3042?

I'll take out the rhel-7-9 image refresh here, as the fix in *this* PR is good and resolves the centos-7 rebuild issue.

**Review by martinpitt — APPROVED** [review]
